### ISSUE TITLE
The logo is not displaying properly in the product  image on the home page.

### ISSUE THREAD

**Issue by RachayyaC** [zysk/Websites_repo#16]
**Steps**
1.login as a user
2. Click on home

**Actual  result**
The logo is not displaying properly in the product image on the home page.
https://i.imgur.com/6nDKice.png

**Expected result**
The logo should display properly on the image.

**Comment by Vishakvm** [comment]
Only Search bar is hiding when we scroll down to the page, this is the default feature of the theme.
