### ISSUE TITLE
In the categories and recent posts the images are not displaying in both windows and android.

### ISSUE THREAD

**Issue by RachayyaC** [zysk/Websites_repo#18]
**Steps**
1. Add a product to cart 
2. Click on the cart icon.
3. in the checkout page verify the categories like design trends, furniture, decoration, and recent posts.

**Actual result**
In the categories and recent posts, the images are not displaying.
C:\Users\Zysk_Hemant\Documents\ShareX\Screenshots\2020-07\KK4ioI2pMD.mp4
C:\Users\Zysk_Hemant\AppData\Local\Microsoft\Windows\INetCache\IE\7XGS0TBH\Screenrecorder-2020-07-14-14-46-08-43[1].mp4

**Expected result**
It should display all the images properly.

**Comment by Vishakvm** [comment]
Removed posts & instagram links form the page.(Not needed for the site)
