### ISSUE TITLE
NGO - wordpress theme search

### ISSUE THREAD

**Issue by kruthinarayan** [zysk/Websites_repo#208]
To search crowd funding  themes in wordpress
Estimated time : 2hrs

**Comment by kruthinarayan** [comment]
Searched for the themes and have finalized one and sent it to varun

**Comment by kruthinarayan** [comment]
https://preview.themeforest.net/item/unity-wordpress-crowdfunding-theme/full_screen_preview/10773175?_ga=2.165212863.1839277217.1601536330-2059913006.1582638475

**Comment by kruthinarayan** [comment]
Have shared 4 themes with Varun and Shilpa via email. Waiting for the response

**Comment by jayashreebai** [comment]
@kruthinarayan  is this reviewed?? If so please add review comments (you or reveiwer) and move it to done
