### ISSUE TITLE
In the portfolio the pages are not displaying properly.

### ISSUE THREAD

**Issue by RachayyaC** [zysk/Websites_repo#4]
**Steps**
1.Login as a user
2. Click on the navigation icon from the left-top corner.
3. Click on portfolio

**Actual result**
The pages not displaying any data.
C:\Users\Zysk_Hemant\AppData\Local\Microsoft\Windows\INetCache\IE\AXN30I32\Screenrecorder-2020-07-11-21-41-35-978[2].mp4

**Expected result**
All the pages should display valid data.

**Comment by Vishakvm** [comment]
This page is not a part of the website, its a theme default page.Removed the page from mobile menu.

**Comment by RachayyaC** [comment]
Retested in android,
The portfolio page is removed from the mobile menu.
