### ISSUE TITLE
In blog page the images are not displaying properly.

### ISSUE THREAD

**Issue by RachayyaC** [zysk/Websites_repo#5]
Steps
1.Login as a user
2. Click on the navigation icon from the left-top corner.
3. Click on blog

Actual result
The images related to the information is not displaying.
C:\Users\Zysk_Hemant\AppData\Local\Microsoft\Windows\INetCache\IE\AXN30I32\Screenrecorder-2020-07-11-21-41-35-978[2].mp4

Expected result
The images should display properly.

**Comment by Vishakvm** [comment]
This page is not a part of the site, its a theme default page.Removed the page from mobile menu.

**Comment by RachayyaC** [comment]
Retested in android,
The blog page is removed from the mobile menu.
